### ISSUE TITLE
Help setting up browsetime with sitespeed.io CI job in ubuntu

### ISSUE THREAD

**Issue by avellayappan** [tobli/browsertime#44]
I have a CI job to run the sitespeed.io in ubuntu - uses xvfb jenkins plugin

Command used to run sitespeed.io:
sitespeed.io -f /var/lib/jenkins/sitespeed.io-2.5.6/bin/urlsNoAds.txt -c firefox -z 1

I see the following error in data/error.log folder and do not get any browsetime information:
An unknown error occurred!
Please attach the following information to a bug report at https://github.com/tobli/browsertime/issues
net.browsertime.tool.BrowserTimeException: Error while running Selenium.
	at net.browsertime.tool.timingrunner.SeleniumTimingRunner.run(SeleniumTimingRunner.java:101)
	at net.browsertime.tool.run.Main.run(Main.java:122)
	at net.browsertime.tool.run.Main.handleCommandLine(Main.java:87)
	at net.browsertime.tool.run.Main.main(Main.java:59)
Caused by: org.openqa.selenium.WebDriverException: Unable to bind to locking port 7054 within 45000 ms
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'sitespeedci-140243', ip: '10.65.251.196', os.name: 'Linux', os.arch: 'amd64', os.version: '3.5.0-23-generic', java.version: '1.7.0_13'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.internal.SocketLock.lock(SocketLock.java:98)
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:84)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:110)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:195)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:190)
	at net.browsertime.tool.webdriver.FirefoxDriverProvider.get(FirefoxDriverProvider.java:31)
	at net.browsertime.tool.webdriver.FirefoxDriverProvider.get(FirefoxDriverProvider.java:13)
	at net.browsertime.tool.timingrunner.SeleniumTimingRunner.run(SeleniumTimingRunner.java:81)
	... 3 more

Any thoughts on what I need to check in the setup?

**Comment by tobli** [comment]
I'm closing this now. So much time has passed, and both sitespeed and browsertime has been re-implemented in a new language since then, and the browsers involved has changed much as well. Please file new bugs for any bugs or errors you're seeing with the current version. Thanks!
