### ISSUE TITLE
Running Sitespeed.io with browsertime for Chrome

### ISSUE THREAD

**Issue by avellayappan** [tobli/browsertime#47]
Have you seen this error while runnng sitespeed.io for chrome using Ubuntu CI:

An unknown error occurred!
Please attach the following information to a bug report at https://github.com/tobli/browsertime/issues
net.browsertime.tool.BrowserTimeException: Error while running Selenium.
	at net.browsertime.tool.timingrunner.SeleniumTimingRunner.run(SeleniumTimingRunner.java:101)
	at net.browsertime.tool.run.Main.run(Main.java:122)
	at net.browsertime.tool.run.Main.handleCommandLine(Main.java:87)
	at net.browsertime.tool.run.Main.main(Main.java:59)
Caused by: org.openqa.selenium.WebDriverException: chrome not reachable
  (Session info: chrome=32.0.1700.102)
  (Driver info: chromedriver=2.9.248304,platform=Linux 3.5.0-23-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 3 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'sitespeedci-140243', ip: '10.65.251.196', os.name: 'Linux', os.arch: 'amd64', os.version: '3.5.0-23-generic', java.version: '1.7.0_13'
Session ID: 56aa0b6d369909e6b045a77184d38763
Driver info: net.browsertime.tool.webdriver.ChromeDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.rephyr}, rotatable=false, locationContextEnabled=true, version=32.0.1700.102, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, nativeEvents=true, webStorageEnabled=true, applicationCacheEnabled=false, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:193)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:463)
	at net.browsertime.tool.timingrunner.SeleniumTimingRunner$1.apply(SeleniumTimingRunner.java:138)
	at net.browsertime.tool.timingrunner.SeleniumTimingRunner$1.apply(SeleniumTimingRunner.java:136)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	at net.browsertime.tool.timingrunner.SeleniumTimingRunner.waitForLoad(SeleniumTimingRunner.java:143)
	at net.browsertime.tool.timingrunner.SeleniumTimingRunner.fetchUrl(SeleniumTimingRunner.java:131)
	at net.browsertime.tool.timingrunner.SeleniumTimingRunner.run(SeleniumTimingRunner.java:83)
	... 3 more

This job used to work before and has been recently failing.  I tried rebooting the machine and it still fails with the same error.

**Comment by tobli** [comment]
This is for the old Java based version, closing!
