### ISSUE TITLE
Add error handling if a Selenium promise fails

### ISSUE THREAD

**Issue by soulgalore** [tobli/browsertime#60]
Today one problem is that BrowserTime can fail silent, if we use the proxy and get a connection refuse like:
<pre>
Error: ECONNREFUSED connect ECONNREFUSED
    at ClientRequest.<anonymous> (/Users/peter/git/bt3/node_modules/selenium-webdriver/http/index.js:145:16)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
</pre>

This happens right now if you are using PhantomJS2 and has the proxy turned on.

**Comment by soulgalore** [comment]
this is fixed
