### ISSUE TITLE
Chrome crashes on Ubuntu (sometimes, puh)

### ISSUE THREAD

**Issue by soulgalore** [tobli/browsertime#70]
When running many many URL:s through sitespeed, it seems like Chrome crashes. Ok, so nothing that Browsertime can fix but maybe the error can be caught? Or should it be caught in sitespeed, hmm.

<pre>
info: Stopping proxy

/home/parallels/.nvm/v0.10.33/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/proxy/mobproxy.js:87
    throw err;
          ^
UnknownError: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.9.248304,platform=Linux 3.13.0-34-generic x86_64)
    at new bot.Error (/home/parallels/.nvm/v0.10.33/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)
    at Object.bot.response.checkResponse (/home/parallels/.nvm/v0.10.33/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
    at /home/parallels/.nvm/v0.10.33/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:152:24
    at /home/parallels/.nvm/v0.10.33/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (/home/parallels/.nvm/v0.10.33/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at notify (/home/parallels/.nvm/v0.10.33/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
    at notifyAll (/home/parallels/.nvm/v0.10.33/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/promise.js:442:7)
    at resolve (/home/parallels/.nvm/v0.10.33/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/promise.js:420:7)
    at fulfill (/home/parallels/.nvm/v0.10.33/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/promise.js:535:5)
    at /home/parallels/.nvm/v0.10.33/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
==== async task ====
WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/home/parallels/.nvm/v0.10.33/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:149:22)
    at Function.webdriver.WebDriver.createSession (/home/parallels/.nvm/v0.10.33/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:123:30)
    at new Driver (/home/parallels/.nvm/v0.10.33/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/chrome.js:477:36)
    at Builder.build (/home/parallels/.nvm/v0.10.33/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/builder.js:303:14)
    at Object.module.exports.getDriver (/home/parallels/.nvm/v0.10.33/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsers/chrome.js:38:56)
    at /home/parallels/.nvm/v0.10.33/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsertime.js:86:66
    at /home/parallels/.nvm/v0.10.33/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:254:17
    at /home/parallels/.nvm/v0.10.33/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:157:25
    at /home/parallels/.nvm/v0.10.33/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:251:21
</pre>

**Comment by soulgalore** [comment]
Adding a fresh dump of this problem:
<pre>
/home/parallels/.nvm/v0.10.35/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/proxy/mobproxy.js:87
    throw err;
          ^
UnknownError: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.9.248304,platform=Linux 3.13.0-34-generic x86_64)
    at new bot.Error (/home/parallels/.nvm/v0.10.35/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)
    at Object.bot.response.checkResponse (/home/parallels/.nvm/v0.10.35/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
    at /home/parallels/.nvm/v0.10.35/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:152:24
    at /home/parallels/.nvm/v0.10.35/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (/home/parallels/.nvm/v0.10.35/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at notify (/home/parallels/.nvm/v0.10.35/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
    at notifyAll (/home/parallels/.nvm/v0.10.35/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/promise.js:442:7)
    at resolve (/home/parallels/.nvm/v0.10.35/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/promise.js:420:7)
    at fulfill (/home/parallels/.nvm/v0.10.35/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/promise.js:535:5)
    at /home/parallels/.nvm/v0.10.35/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
==== async task ====
WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/home/parallels/.nvm/v0.10.35/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:149:22)
    at Function.webdriver.WebDriver.createSession (/home/parallels/.nvm/v0.10.35/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:123:30)
    at new Driver (/home/parallels/.nvm/v0.10.35/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/chrome.js:477:36)
    at Builder.build (/home/parallels/.nvm/v0.10.35/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/builder.js:303:14)
    at Object.module.exports.getDriver (/home/parallels/.nvm/v0.10.35/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsers/chrome.js:31:56)
    at /home/parallels/.nvm/v0.10.35/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsertime.js:86:66
    at /home/parallels/.nvm/v0.10.35/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:254:17
    at /home/parallels/.nvm/v0.10.35/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:157:25
    at /home/parallels/.nvm/v0.10.35/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:251:21
</pre>

**Comment by soulgalore** [comment]
Here's the selenium issue:
https://code.google.com/p/selenium/issues/detail?id=8261

**Comment by soulgalore** [comment]
Got some more info here. We got a chrome that's not reachable: 
<pre>
2015-02-19T06:19:03.099Z - error: chrome not reachable
  (Session info: chrome=40.0.2214.111)
  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Linux 3.13.0-40-generic x86_64)
</pre>

And we git double callbacks called:
<pre>
2015-02-19T06:19:03.120Z - error: Error: Callback was already called.
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:30:31
    at /usr/local/lib/node_modules/sitespeed.io/lib/analyze/browsertime.js:164:14
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsertime.js:54:5
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:254:17
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:151:21
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:251:21
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:615:34
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsertime.js:69:16
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:254:17
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:151:21
</pre>

**Comment by soulgalore** [comment]
ok, now e catch the error (even if Chrome hangs) and call the callback with an error. lets keep it like that for a while.
