### ISSUE TITLE
Got logging.js error at first time

### ISSUE THREAD

**Issue by fastzhong** [tobli/browsertime#86]
Hi, on my windows laptop, fresh installation and hit error immediately: 

C:\lun\ibm\project\FASTER>node -v
v0.12.4

C:\lun\ibm\project\FASTER>npm -v
2.10.1

C:\lun\ibm\project\FASTER>cd sitespeed

C:\lun\ibm\project\FASTER\sitespeed>npm install browsertime -g

C:\lun\ibm\project\FASTER\sitespeed>browsertime -u http://www.google.com

fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'C:\lun\ibm\project\FASTER\sitespeed\webdriver\logging.js'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.Context.closure.goog.retrieveAndExecModule_ (C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\browsertime\node_modules\selenium-webdriver\_base.js:129:23)
    at <anonymous>:1:6
    at Object.exports.runInContext (vm.js:64:17)
    at Context.closure.closure.vm.createContext.CLOSURE_IMPORT_SCRIPT (C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\browsertime\node_modules\selenium-webdriver\_base.js:101:12)
    at Object.goog.importScript_ (C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\browsertime\node_modules\selenium-webdriver\lib\goog\base.js:873:9)
    at Object.goog.importModule_ (C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\browsertime\node_modules\selenium-webdriver\lib\goog\base.js:894:14)
    at Object.goog.writeScripts_ (C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\browsertime\node_modules\selenium-webdriver\lib\goog\base.js:1251:16)

Anything wrong?

**Comment by tobli** [comment]
Hi @fastzhong!
Thanks for reporting. None of the regular contributors use Windows, so it doesn't get a lot of testing. Your particular issue might have been solved by a Selenium patch that was released today. I'll try and get a release out with that shortly.

Best,
//Tobias

**Comment by soulgalore** [comment]
also in sitespeed: https://github.com/sitespeedio/sitespeed.io/issues/683

**Comment by soulgalore** [comment]
Fixed now in 0.9.8.
