### ISSUE TITLE
The upgrade of Browsermob-proxy-api breaks setting connection speed

### ISSUE THREAD

**Issue by soulgalore** [tobli/browsertime#89]
<pre>
$ bin/browsertime.js -u http://www.sitespeed.io --connection mobile3g
Starting proxy on port 2001, will wait at most 15000 ms
Catched an uncaught exception:TypeError: Property 'limit' of object #<Object> is not a functionTypeError: Property 'limit' of object #<Object> is not a function
    at /Users/peter/git/browsertime/lib/proxy/mobproxy.js:176:9
    at /Users/peter/git/browsertime/node_modules/async/lib/async.js:735:13
    at iterate (/Users/peter/git/browsertime/node_modules/async/lib/async.js:253:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/Users/peter/git/browsertime/node_modules/async/lib/async.js:272:9)
    at Object.async.series (/Users/peter/git/browsertime/node_modules/async/lib/async.js:734:15)
    at /Users/peter/git/browsertime/lib/proxy/mobproxy.js:187:13
    at IncomingMessage.<anonymous> (/Users/peter/git/browsertime/node_modules/browsermob-proxy-api/index.js:186:46)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
</pre>

**Comment by tobli** [comment]
Right, I see the problem. Aliasing a function in js didn't quite work as I thought it did... Changing browsertime to call p.setLimit should work, I'll prepare a patch to bmp-api as soon as I get the chance to sit down with the code.

**Comment by soulgalore** [comment]
np, I'll do a fix for now :)

**Comment by parangsjo** [comment]
Hi,
You need to take a look at that nice and beautiful stuff I came across yesterday, it's really cool! Here is the link <http://teshozendo.tjstark.com/xybbcwle>
Best, pa@rangsjo.com

**Comment by parangsjo** [comment]
Hi,

Have you ever seen that stuff? That's exetremely interesting, just take a look here <http://thumofequo.aplustireandauto.net/xyhmrec>

Later, pa@rangsjo.com
