### ISSUE TITLE
Custom headers cause failures

### ISSUE THREAD

**Issue by okor** [tobli/browsertime#97]
Passing some test headers here with results.

```
 ~/Projects/voxmedia/lightbike $ browsertime -u http://www.theverge.com --headers {"name":"value"}
Starting proxy on port 2001, will wait at most 15000 ms
Error from server: 500
Stopping proxy
 ~/Projects/voxmedia/lightbike $ browsertime -u http://www.theverge.com --headers {name:value}
Starting proxy on port 2001, will wait at most 15000 ms
Error from server: 500
Stopping proxy
```

Relevant portion of browsermobproxy.log

```
2015-12-04T20:25:56.828Z - error: stderr:WARN 12/04 20:25:56 o.e.j.u.log          - /proxy/2000/headers
com.google.sitebricks.routing.EventDispatchException: Exception [RuntimeException - "Unable to obtain input stream from servlet request (was it already used or closed elsewhere?). Error:
Can not instantiate value of type java.util.LinkedHashMap from String value ('{name:value}'); no single-String constructor/factory method
 at [Source: org.eclipse.jetty.server.HttpInput@7904a5c; line: 1, column: 1]"] thrown by event method [public com.google.sitebricks.headless.Reply net.lightbody.bmp.proxy.bricks.ProxyResource.updateHeaders(int,com.google.sitebricks.headless.Request)]

at com.google.sitebricks.ServletRequestProvider$1$1.as(ServletRequestProvider.java:67)
(See below for entire trace.)

	at com.google.sitebricks.routing.DefaultPageBook$MethodTuple.call(DefaultPageBook.java:830)
	at com.google.sitebricks.routing.DefaultPageBook$MethodTuple.call(DefaultPageBook.java:805)
	at com.google.sitebricks.routing.DefaultPageBook$PageTuple.callAction(DefaultPageBook.java:624)
	at com.google.sitebricks.routing.DefaultPageBook$PageTuple.doMethod(DefaultPageBook.java:603)
	at com.google.sitebricks.routing.WidgetRoutingDispatcher.fireEvent(WidgetRoutingDispatcher.java:171)
	at com.google.sitebricks.routing.WidgetRoutingDispatcher.bindAndReply(WidgetRoutingDispatcher.java:102)
	at com.google.sitebricks.routing.WidgetRoutingDispatcher.dispatch(WidgetRoutingDispatcher.java:88)
	at com.google.sitebricks.DebugModeRoutingDispatcher.dispatch(DebugModeRoutingDispatcher.java:56)
	at com.google.sitebricks.SitebricksFilter.doFilter(SitebricksFilter.java:62)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.google.sitebricks.HiddenMethodFilter.doFilter(HiddenMethodFilter.java:70)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1323)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:474)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:935)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:404)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:870)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:346)
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1068)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:807)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:220)
	at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:520)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:528)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.sitebricks.routing.DefaultPageBook$MethodTuple.call(DefaultPageBook.java:820)
	... 34 more
Caused by: java.lang.RuntimeException: Unable to obtain input stream from servlet request (was it already used or closed elsewhere?). Error:
Can not instantiate value of type java.util.LinkedHashMap from String value ('{name:value}'); no single-String constructor/factory method
 at [Source: org.eclipse.jetty.server.HttpInput@7904a5c; line: 1, column: 1]
	at com.google.sitebricks.ServletRequestProvider$1$1.as(ServletRequestProvider.java:67)
	at net.lightbody.bmp.proxy.bricks.ProxyResource.updateHeaders(ProxyResource.java:248)
	... 39 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type java.util.LinkedHashMap from String value ('{name:value}'); no single-String constructor/factory method
 at [Source: org.eclipse.jetty.server.HttpInput@7904a5c; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:770)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:277)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromString(ValueInstantiator.java:178)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3066)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2207)
	at com.google.sitebricks.client.transport.JacksonJsonTransport.in(JacksonJsonTransport.java:31)
	at com.google.sitebricks.ServletRequestProvider$1$1.as(ServletRequestProvider.java:63)
	... 40 more
```

Seems like a parser error in a Java lib. Might be their problem but thought I'd ask. Running latest Chrome on Yosemite. I'm able to use browsertime without custom headers just fine.

**Comment by okor** [comment]
Might be able to try a newer version of Browsermob https://github.com/sitespeedio/bmp-wrapper/blob/master/pom.xml#L10-L11 They seem to be recommending version 2.1.0-beta-3 https://github.com/lightbody/browsermob-proxy

**Comment by tobli** [comment]
Hi Jason!
Thanks for reporting. This was a bug in parsing of the --headers option (--connectionRaw had the same issue). I just pushed 0.12.1 to fix it. When running Browsertime from within Sitespeed.io we bypass the cli and use the node api directly. Therefor this was undetected. Thanks again!

**Comment by okor** [comment]
I can confirm the fix works on version 0.12.1, with the cli, if you quote the JSON propertly as noted here https://github.com/tobli/browsertime/commit/59028dabf9f2fc9bc12cf45efce23d63fdaae4c1

Example for Googlers: `browsertime -u http://www.google.com --headers '{"name":"value"}'`

Thank you @tobli : )

**Comment by tobli** [comment]
Thanks @okor 
I'd love feedback on whether providing json on the command line is actually a good idea. It's quite cumbersome to get right, so providing the json in a separate file might be preferable. On the other hand, being able to provide everything as one command, with no extra dependencies, has it's upsides as well.

**Comment by okor** [comment]
@tobli In the interest of consistency, I'd say leave the JSON inline as it is now. Most CLI are inline focused. If you do add a JSON file option I'd keep the stuff that is already there.

I'm writing a thing that iterates over a list and does stuff with browsertime for each item. So passing a JSON file would be more of a pain. So inline also works better for my specific use case as well.
